version: "3.8"
services: 
    frontend:
        container_name: frontend
        tty: true
        build:
            context: ./client
            dockerfile: ./Dockerfile
        volumes: 
            - ./client:/app
        ports: 
            - "3000:3000"
        