image: tshio/node-pipelines:latest

pipelines:
  default:
    - step:
        caches:
          - node
        services:
          - docker
        script:
          - cp .env.dist .env
          - npm run docker-build
          - npm run lint
          - npm run units
          - npm run integration
